### ISSUE TITLE
0.6.7?

### ISSUE THREAD

**Issue by ches** [n8han/giter8#149]
The Maven resolver looks very useful. Is there more you're wanting to include in an 0.6.7 release, or could you at least update the Conscript launchconfig such that `cs n8han/giter8 --branch 0.6.7` would let us install it as a prerelease?

Thanks!

**Comment by n8han** [comment]
It's published!

**Comment by ches** [comment]
Thank you!

Now I've got a show-stopping bug with 0.6.7—off to reporting that :grin:
