### ISSUE TITLE
Properties are computed out-of-order in 0.6.7 (causing breakage)

### ISSUE THREAD

**Issue by ches** [n8han/giter8#151]
I installed 0.6.7 eager to use the new Maven resolver in my templates, but unfortunately it is prompting for the values in my `default.properties` out of order, causing substitutions to break (no use of the Maven resolver involved yet FYI, this is out of the box on templates I used previously).

Here's how applying my template worked in 0.6.6 (and after restoring back to it):

```
$ g8 file://scala-project.g8

Scala project with a basic, minimal SBT build configuration.

name [New Project]:
organization [org.example]:
package [org.example.newproject]:
scala_version [2.11.4]:
sbt_version [0.13.7]:
scalatest_version [2.2.2]:

Template applied in ./new-project
```

And here's here's what happens with 0.6.7:

```
$ g8 file://scala-project.g8

Scala project with a basic, minimal SBT build configuration.

scalatest_version [2.2.2]:
sbt_version [0.13.7]:
scala_version [2.11.4]:
context [anonymous] 1:1 attribute organization isn't defined
context [anonymous] 1:16 attribute name isn't defined
package [.]:
organization [org.example]:
name [New Project]:

Template applied in ./new-project
```

Looks like the order is exactly inverted, actually—missing a reverse after recursing somewhere perhaps?

For reference, the template is [here][1]. It's quite basic.

[1]: https://github.com/ches/scala-project.g8

**Comment by n8han** [comment]
Oh dear. Any help identifying the source of the regression would be much appreciated, so I can release a fix before many people upgrade. There were the two PRs in the last release, I'd suspect #144 for this first.

**Comment by ches** [comment]
I tried to have a look over the changes earlier but I'm not very familiar with the code yet, especially since #144 doesn't seem to make any obvious behavior change of this nature unless it comes from the upstream dependencies. @butlermh could probably answer that faster. Actually a bit more suspicious that #136 processes the `OrderedProperties`—@xuwei-k any obvious bug standing out?

**Comment by butlermh** [comment]
Wierd - if I build 0.6.7 it works but if I get the latest version via Conscript it doesn't - any ideas what I am doing wrong?

    cd /tmp
    git clone git@github.com:n8han/giter8.git
    git checkout 0.6.7
    sbt publish-local
    cs --local n8han/giter8/0.6.7-SNAPSHOT
    cd ..
    g8 git://github.com/ches/scala-project.g8

        Scala project with a basic, minimal SBT build configuration. 

        name [New Project]: 
        organization [org.example]: 
        package [org.example.newproject]: 
        scala_version [2.11.4]: 
        sbt_version [0.13.7]: 
        scalatest_version [2.2.2]: 

    Template applied in ./new-project

    cs n8han/giter8
    rm -rf new-project
    g8 git://github.com/ches/scala-project.g8

        Scala project with a basic, minimal SBT build configuration. 

        scalatest_version [2.2.2]: 
        sbt_version [0.13.7]: 
        scala_version [2.11.4]: 
        context [anonymous] 1:1 attribute organization isn't defined
        context [anonymous] 1:16 attribute name isn't defined
        package [.]: 
        organization [org.example]: 
        name [New Project]: 

        Template applied in ./new-project

**Comment by butlermh** [comment]
OK I can replicate the error locally now ...

**Comment by butlermh** [comment]
I believe the problem is here: 

https://github.com/n8han/giter8/commit/507a61a09408e1f15e2f5a843f1c0486888fcc5d#diff-c6e29866d1d713f1c32f35d926ae1f50R216

**Comment by butlermh** [comment]
I tried [reverting some code](https://github.com/butlermh/giter8/commit/257816feb69932de36d2a9fa4ad4ac58272360a4) and that fixed the problem (although this breaks the new Maven resolver) .. so I think that's where the problem is.

**Comment by n8han** [comment]
Thanks for investigating @butlermh, and sorry for wrongly accusing your PR. ;) I'll see if I can fix the problem.

**Comment by ches** [comment]
Thanks for the quick fix gents!
